# Generated by Django 4.0.6 on 2022-09-05 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
        ('operacional', '0002_remove_coleta_consignatario_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtc',
            name='consignatario_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consigDtc', to='parceiros.parceiros'),
        ),
        migrations.AlterField(
            model_name='dtc',
            name='redespacho_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redespDtc', to='parceiros.parceiros'),
        ),
    ]
