# Generated by Django 4.0.6 on 2022-09-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0003_alter_dtc_consignatario_fk_alter_dtc_redespacho_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('origemCidade', models.CharField(max_length=20)),
                ('origemUf', models.CharField(max_length=2)),
                ('destinoCidade', models.CharField(max_length=20)),
                ('destinoUf', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='dtc',
            name='tipoFrete',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dtc',
            name='rota_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotaDtc', to='operacional.rota'),
        ),
    ]
