# Generated by Django 4.0.6 on 2022-09-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0005_remove_coleta_dtc_fk_dtc_coleta_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtc',
            name='coleta_fk',
        ),
        migrations.AddField(
            model_name='coleta',
            name='dtc_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coletaDtc', to='operacional.dtc'),
        ),
    ]
