# Generated by Django 4.0.6 on 2022-09-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0006_remove_dtc_coleta_fk_coleta_dtc_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='notaFiscal',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='cubM3',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
