# Generated by Django 4.0.6 on 2022-09-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0007_coleta_notafiscal_alter_coleta_cubm3'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='impresso',
            field=models.BooleanField(default=False),
        ),
    ]
