# Generated by Django 4.0.6 on 2022-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0009_remove_coleta_dtc_fk_dtc_coleta_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='mercadoria',
            field=models.CharField(default='Diversos', max_length=20),
        ),
        migrations.AlterField(
            model_name='coleta',
            name='contato',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
