# Generated by Django 4.0.6 on 2022-09-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0010_coleta_mercadoria_alter_coleta_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='horario',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
