# Generated by Django 4.0.6 on 2022-10-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0011_coleta_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=30)),
                ('uf', models.CharField(max_length=2)),
                ('rota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coletaDtc', to='operacional.rota')),
            ],
        ),
    ]
