# Generated by Django 4.0.6 on 2022-10-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0013_municipios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipios',
        ),
    ]
