# Generated by Django 4.0.6 on 2023-01-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0014_delete_municipios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtc',
            name='tipoFrete',
            field=models.IntegerField(default=2),
        ),
    ]
