# Generated by Django 4.0.6 on 2023-01-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
        ('operacional', '0015_alter_dtc_tipofrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtc',
            name='tomador_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tomadoDtc', to='parceiros.parceiros'),
        ),
    ]
