# Generated by Django 4.0.6 on 2023-01-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
        ('operacional', '0016_dtc_tomador_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtc',
            name='destinatario_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destDtc', to='parceiros.parceiros'),
        ),
        migrations.AlterField(
            model_name='dtc',
            name='remetente_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remetDtc', to='parceiros.parceiros'),
        ),
    ]
