# Generated by Django 4.1.7 on 2023-08-17 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0019_frete_dtc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frete_dtc',
            name='dataHora',
        ),
        migrations.RemoveField(
            model_name='frete_dtc',
            name='nome',
        ),
    ]
