# Generated by Django 4.1.7 on 2023-08-22 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacional', '0020_remove_frete_dtc_datahora_remove_frete_dtc_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frete_dtc',
            name='dtc_fk',
        ),
        migrations.AddField(
            model_name='dtc',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dtc',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dtc',
            name='frete_dtc_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frete_dtc', to='operacional.frete_dtc'),
        ),
        migrations.AddField(
            model_name='dtc',
            name='usuario_cadastro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criador_dtc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dtc',
            name='usuario_ultima_atualizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizador_frete_dtc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='frete_dtc',
            name='usuario_cadastro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastrado_dtc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='frete_dtc',
            name='usuario_ultima_atualizacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alterou_dtc', to=settings.AUTH_USER_MODEL),
        ),
    ]
