# Generated by Django 4.1.7 on 2023-08-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0021_remove_frete_dtc_dtc_fk_dtc_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtc',
            name='data_cadastro',
            field=models.DateTimeField(null=True),
        ),
    ]
