# Generated by Django 4.1.7 on 2023-08-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0023_cte_remove_dtc_frete_dtc_fk_remove_dtc_redespacho_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cte',
            name='data_cadastro',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cte',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(null=True),
        ),
    ]
