# Generated by Django 4.1.7 on 2024-01-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0025_emissor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coleta',
            name='status',
            field=models.CharField(default='Em aberto', max_length=30, null=True),
        ),
    ]
