# Generated by Django 4.1.7 on 2024-01-22 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parceiros', '0001_initial'),
        ('operacional', '0026_coleta_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciot', models.CharField(blank=True, max_length=20, null=True)),
                ('validade_antt', models.DateField(blank=True, null=True)),
                ('tipo_proprietario', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietario_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proprietario_criado_por', to=settings.AUTH_USER_MODEL)),
                ('parceiro_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parceiro_proprietario', to='parceiros.parceiros')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('ano_fabricacao', models.PositiveIntegerField()),
                ('cor', models.CharField(max_length=20)),
                ('renavam', models.CharField(max_length=20, unique=True)),
                ('chassi', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculo_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculo_criado_por', to=settings.AUTH_USER_MODEL)),
                ('proprietario_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proprietario_veiculo', to='operacional.proprietario')),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('filiacao_pai', models.CharField(blank=True, max_length=255, null=True)),
                ('filiacao_mae', models.CharField(blank=True, max_length=255, null=True)),
                ('cnh_numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('cnh_categoria', models.CharField(blank=True, max_length=5, null=True)),
                ('cnh_validade', models.DateField(blank=True, null=True)),
                ('numero_registro_cnh', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista_criado_por', to=settings.AUTH_USER_MODEL)),
                ('parceiro_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parceiro_motorista', to='parceiros.parceiros')),
            ],
        ),
    ]
