# Generated by Django 4.1.7 on 2024-01-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0027_proprietario_veiculo_motorista'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprietario',
            old_name='ciot',
            new_name='antt',
        ),
    ]
