# Generated by Django 4.1.7 on 2024-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0028_rename_ciot_proprietario_antt'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.PositiveIntegerField(default=1900),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='capacidade_cubica',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='capacidade_kg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='numero_frota',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='numero_rastreador',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tara',
            field=models.FloatField(null=True),
        ),
    ]
