# Generated by Django 4.1.7 on 2024-02-13 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0029_veiculo_ano_modelo_veiculo_capacidade_cubica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Carroceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carroceria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_combustivel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_veiculo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ano_fabricacao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='ano_modelo',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.CharField(default='00/00', max_length=5),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='operacional.marca'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_carroceria_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carroceria', to='operacional.tipo_carroceria'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_combustivel_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combustivel', to='operacional.tipo_combustivel'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_veiculo_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='operacional.tipo_veiculo'),
        ),
    ]
