# Generated by Django 4.1.7 on 2024-02-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0031_veiculo_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='renavam',
            field=models.CharField(max_length=20),
        ),
    ]
