# Generated by Django 4.1.7 on 2024-02-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0032_alter_veiculo_chassi_alter_veiculo_renavam'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='dt_primeira_cnh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='pis',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='motorista',
            name='validade_toxicologico',
            field=models.DateField(blank=True, null=True),
        ),
    ]
