# Generated by Django 4.1.7 on 2024-02-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0033_motorista_dt_primeira_cnh_motorista_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='dt_emissao_cnh',
            field=models.DateField(blank=True, null=True),
        ),
    ]
