# Generated by Django 4.1.7 on 2024-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0035_alter_motorista_cnh_numero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia_manifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocorrencia', models.CharField(max_length=70)),
            ],
        ),
    ]
