# Generated by Django 4.1.7 on 2024-02-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0036_ocorrencia_manifesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=255)),
            ],
        ),
    ]
