# Generated by Django 4.1.7 on 2024-02-29 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacional', '0037_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtcManifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtc_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.dtc')),
            ],
        ),
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_previsão_inicio', models.DateTimeField(null=True)),
                ('data_previsão_chegada', models.DateTimeField(null=True)),
                ('frete_carreteiro', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('frete_adiantamento', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('lacres', models.CharField(max_length=100, null=True)),
                ('averbacao', models.CharField(max_length=20, null=True)),
                ('liberacao', models.CharField(max_length=20, null=True)),
                ('observacao', models.TextField(null=True)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_ultima_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dtc', models.ManyToManyField(null=True, through='operacional.DtcManifesto', to='operacional.dtc')),
                ('emissor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.emissor')),
                ('motoristas', models.ManyToManyField(null=True, to='operacional.motorista')),
                ('rota_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.rota')),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criador_manifesto', to=settings.AUTH_USER_MODEL)),
                ('usuario_ultima_atualizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizador_manifesto', to=settings.AUTH_USER_MODEL)),
                ('veiculos', models.ManyToManyField(null=True, to='operacional.veiculo')),
            ],
        ),
        migrations.AddField(
            model_name='dtcmanifesto',
            name='manifesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.manifesto'),
        ),
        migrations.AddField(
            model_name='dtcmanifesto',
            name='tipo_manifesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.ocorrencia_manifesto'),
        ),
    ]
