# Generated by Django 4.1.7 on 2024-03-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0039_manifestomodel_remove_manifesto_dtc_emissor_aliquota_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManifestoModel',
        ),
    ]
