# Generated by Django 4.1.7 on 2024-03-20 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacional', '0040_delete_manifestomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DtcManifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_ultima_atualizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dtc_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.dtc')),
                ('manifesto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.manifesto')),
                ('ocorrencia_manifesto_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.ocorrencia_manifesto')),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criador_dtc_manifesto', to=settings.AUTH_USER_MODEL)),
                ('usuario_ultima_atualizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atualizador_dtc_manifesto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('dtc_fk', 'manifesto_fk', 'ocorrencia_manifesto_fk')},
            },
        ),
    ]
