# Generated by Django 4.1.7 on 2024-03-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0041_dtcmanifesto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dtcmanifesto',
            unique_together={('dtc_fk', 'manifesto_fk')},
        ),
    ]
