# Generated by Django 4.1.7 on 2024-03-30 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operacional', '0043_cte_chave_cte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carta_frete', models.CharField(blank=True, max_length=255)),
                ('frete_contratado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_emissao_contrato', models.DateField(blank=True, null=True)),
                ('numero_ciot', models.CharField(blank=True, max_length=255)),
                ('valor_pedagio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_coleta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('outros_creditos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ir_retido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sest_senat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adiantamento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('outros_descontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frete_bruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_descontos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frete_a_pagar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contrato_obs', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(null=True)),
                ('data_ultima_atualizacao', models.DateTimeField(null=True)),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastrado_contrato', to=settings.AUTH_USER_MODEL)),
                ('usuario_ultima_atualizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alterou_contrato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
