# Generated by Django 4.1.7 on 2024-03-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0044_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='contrato_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operacional.contrato'),
        ),
    ]
