# Generated by Django 4.1.7 on 2024-04-01 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0046_remove_contrato_numero_carta_frete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='contrato_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.contrato'),
        ),
    ]
