# Generated by Django 4.1.7 on 2024-04-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_municipios'),
        ('operacional', '0047_alter_manifesto_contrato_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='endereco_destino_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_destino_fk', to='enderecos.enderecos'),
        ),
        migrations.AddField(
            model_name='rota',
            name='endereco_origem_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco_origem_fk', to='enderecos.enderecos'),
        ),
    ]
