# Generated by Django 4.1.7 on 2024-04-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0048_rota_endereco_destino_fk_rota_endereco_origem_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='nome',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
