# Generated by Django 5.0.6 on 2024-06-11 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0049_alter_rota_nome'),
        ('parceiros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota_fiscal_Caio_Transportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=50)),
                ('num_nf', models.CharField(max_length=20)),
                ('data_emissao', models.DateField()),
                ('natureza', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=20)),
                ('peso', models.CharField(max_length=20)),
                ('valor_nf', models.CharField(max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('destinatario_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_nfe', to='parceiros.parceiros')),
                ('remetente_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remetente_nfe', to='parceiros.parceiros')),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_cadastradas_caio', to=settings.AUTH_USER_MODEL)),
                ('usuario_ultima_atualizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_fiscais_atualizadas_caio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
