# Generated by Django 5.0.6 on 2024-06-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0051_alter_nota_fiscal_caio_transportes_natureza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota_fiscal_caio_transportes',
            name='valor_nf',
            field=models.IntegerField(default=1),
        ),
    ]
