# Generated by Django 5.0.6 on 2024-06-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0052_alter_nota_fiscal_caio_transportes_valor_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota_fiscal_caio_transportes',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='nota_fiscal_caio_transportes',
            name='valor_nf',
            field=models.CharField(max_length=20),
        ),
    ]
