# Generated by Django 5.0.6 on 2024-06-14 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0054_ocorrencianotasfiscais'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OcorrenciaNotasFiscais',
            new_name='TipoOcorrencias',
        ),
    ]
