# Generated by Django 5.0.6 on 2024-06-14 15:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0055_rename_ocorrencianotasfiscais_tipoocorrencias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaNotasFiscais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=70)),
                ('data', models.DateField(null=True)),
                ('imagem_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencia_atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencia_criado_por', to=settings.AUTH_USER_MODEL)),
                ('nota_fiscal_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nf_ocorrencia', to='operacional.nota_fiscal_caio_transportes')),
                ('ocorrencia_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_ocorrencia', to='operacional.tipoocorrencias')),
            ],
        ),
    ]
