# Generated by Django 5.0.6 on 2024-06-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0057_manifestocaiotransportes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencianotasfiscais',
            name='observacao',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
