# Generated by Django 4.0.6 on 2023-01-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacional', '0014_delete_municipios'),
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaFrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTabela', models.IntegerField(default=1)),
                ('descricao', models.CharField(max_length=15)),
                ('icmsIncluso', models.BooleanField(default=True)),
                ('bloqueada', models.BooleanField(default=False)),
                ('freteMinimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('frete', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipoCalculo', models.IntegerField()),
                ('adValor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gris', models.DecimalField(decimal_places=2, max_digits=5)),
                ('despacho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('outros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pedagio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipoPedagio', models.IntegerField()),
                ('cubagem', models.BooleanField(default=True)),
                ('fatorCubagem', models.IntegerField()),
                ('parceiro', models.ManyToManyField(blank=True, to='parceiros.parceiros')),
                ('rota_fk', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='operacional.rota')),
            ],
        ),
        migrations.CreateModel(
            name='TabelaFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixaInicial', models.IntegerField()),
                ('faixaFinal', models.IntegerField()),
                ('vlrFaixa', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('tblVinculada', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.tabelafrete')),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField()),
                ('qtde', models.IntegerField()),
                ('vlrNf', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('m3', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('totalFrete', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('freteValor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('adValor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('gris', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('despacho', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('outros', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pedagio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('dtc_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.dtc')),
            ],
        ),
    ]
