# Generated by Django 4.0.6 on 2023-01-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_tabelafrete_aliquotaicms'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscalCotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtde', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('m3', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('pesoCub', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('chaveDeAcesso', models.CharField(max_length=44)),
                ('cotacao_fk', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='comercial.cotacao')),
            ],
        ),
    ]
