# Generated by Django 4.0.6 on 2023-01-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_notafiscalcotacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotaFiscalCotacao',
        ),
    ]
