# Generated by Django 4.0.6 on 2023-01-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_delete_notafiscalcotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='aliquota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='baseDeCalculo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='contato',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='formaDeCalculo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='icmsIncluso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='icmsRS',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='nome',
            field=models.CharField(max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='numNf',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='pesoFaturado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='rota_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotaCotacao', to='comercial.tabelafrete'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='tabela_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabelaCotacao', to='comercial.tabelafrete'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='tipoMercadoria',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
