# Generated by Django 4.0.6 on 2023-01-16 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0014_delete_municipios'),
        ('comercial', '0006_cotacao_aliquota_cotacao_basedecalculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='nome',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='rota_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotaCotacao', to='operacional.rota'),
        ),
    ]
