# Generated by Django 4.0.6 on 2023-03-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0017_alter_dtc_destinatario_fk_alter_dtc_remetente_fk'),
        ('comercial', '0007_alter_cotacao_nome_alter_cotacao_rota_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelafrete',
            name='rota',
            field=models.ManyToManyField(blank=True, related_name='tabelaRota', to='operacional.rota'),
        ),
    ]
