# Generated by Django 4.0.6 on 2023-03-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_tabelafrete_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='vlrColeta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
