# Generated by Django 4.1.7 on 2023-03-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_cotacao_vlrcoleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='dataHora',
            field=models.DateTimeField(null=True),
        ),
    ]
