# Generated by Django 4.1.7 on 2023-07-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_cotacao_datahora'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='observacao',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
