# Generated by Django 4.1.7 on 2023-07-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_cotacao_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='observacao',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
