# Generated by Django 4.2.3 on 2023-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_alter_cotacao_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='adValor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='aliquota',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='baseDeCalculo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='despacho',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='fretePeso',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='gris',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='icmsRS',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='m3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='outros',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='pedagio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='pesoFaturado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='totalFrete',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='vlrColeta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='vlrNf',
            field=models.FloatField(default=0.0),
        ),
    ]
