# Generated by Django 4.1.7 on 2023-08-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_alter_cotacao_advalor_alter_cotacao_aliquota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='tabela_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabelaCotacao', to='comercial.tabelafrete'),
        ),
    ]
