# Generated by Django 4.1.7 on 2024-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0014_alter_cotacao_tabela_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='em_uso',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
