# Generated by Django 4.1.7 on 2024-01-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_cotacao_em_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='usuario_cadastro',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='em_uso',
            field=models.BooleanField(default=False, max_length=15, null=True),
        ),
    ]
