# Generated by Django 4.1.7 on 2024-01-04 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0025_emissor'),
        ('comercial', '0016_cotacao_usuario_cadastro_alter_cotacao_em_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='cotaca_aplicada_no_cte_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.cte'),
        ),
    ]
