# Generated by Django 4.0.6 on 2022-08-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0002_enderecos_complemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_cpf', models.CharField(max_length=18)),
                ('raz_soc', models.CharField(max_length=50)),
                ('nome_fantasia', models.CharField(max_length=50)),
                ('insc_est', models.CharField(max_length=30)),
                ('observacao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('endereco_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enderecos.enderecos')),
            ],
        ),
    ]
