# Generated by Django 5.0.6 on 2024-06-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiros',
            name='nome_fantasia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
