# Generated by Django 5.0.6 on 2024-06-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_municipios'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecos',
            name='lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enderecos',
            name='lng',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
