# Generated by Django 4.0.6 on 2022-07-31 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_contato', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fone_email_etc', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('envio', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contatos.tipo_contatos')),
            ],
        ),
    ]
